In [1]:
import pandas as pd
import numpy as np

In [ ]:
student_mat = pd.read_csv(data\raw\"student-mat.csv", delimiter=";")
student_por = pd.read_csv(data\raw\"student-por.csv", delimiter=";")
print(f"Math shape: {student_mat.shape}")
print(f"Portuguese shape: {student_por.shape}")
print("\n--- Math dataset info ---")
student_mat.info()
print("Missing Values(mat):")
print(student_mat.isna().sum().sum())
print("Duplicated Rows(mat):")
print(student_mat.duplicated().sum())
print("\n--- Portuguese dataset info ---")
student_por.info()
print("Missing Values(por):")
print(student_por.isna().sum().sum())
print("Duplicated Rows(por):")
print(student_por.duplicated().sum())

<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:2: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:2: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\Hp\AppData\Local\Temp\ipykernel_9096\3132080082.py:1: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  student_mat = pd.read_csv("data\raw\student-mat.csv", delimiter=";")
C:\Users\Hp\AppData\Local\Temp\ipykernel_9096\3132080082.py:2: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  student_por = pd.read_csv("data\raw\student-por.csv", delimiter=";")

OSError: [Errno 22] Invalid argument: 'data\raw\\student-mat.csv'

In [ ]:
categorical_columns = student_mat.select_dtypes(include="object").columns.intersection(student_por.select_dtypes(include="object").columns)
for column in categorical_columns:
    print(f"--{column}--")
    mat_s = (student_mat[column].value_counts(normalize=True)*100).round(1)
    por_s = (student_por[column].value_counts(normalize=True)*100).round(1)
    comparison_df = pd.concat({"Math (%)": mat_s, "Portuguese (%)": por_s}, axis=1).fillna(0)
    print(comparison_df)
    print("\n")

--school--
        Math (%)  Portuguese (%)
school
GP          88.4            65.2
MS          11.6            34.8


--sex--
     Math (%)  Portuguese (%)
sex
F        52.7            59.0
M        47.3            41.0


--address--
         Math (%)  Portuguese (%)
address
U            77.7            69.6
R            22.3            30.4


--famsize--
         Math (%)  Portuguese (%)
famsize
GT3          71.1            70.4
LE3          28.9            29.6


--Pstatus--
         Math (%)  Portuguese (%)
Pstatus
T            89.6            87.7
A            10.4            12.3


--Mjob--
          Math (%)  Portuguese (%)
Mjob
other         35.7            39.8
services      26.1            21.0
at_home       14.9            20.8
teacher       14.7            11.1
health         8.6             7.4


--Fjob--
          Math (%)  Portuguese (%)
Fjob
other         54.9            56.5
services      28.1            27.9
teacher        7.3             5.5
at_home        5.1             6.5
health         4.6             3.5


--reason--
            Math (%)  Portuguese (%)
reason
course          36.7            43.9
home            27.6            23.0
reputation      26.6            22.0
other            9.1            11.1


--guardian--
          Math (%)  Portuguese (%)
guardian
mother        69.1            70.1
father        22.8            23.6
other          8.1             6.3


--schoolsup--
           Math (%)  Portuguese (%)
schoolsup
no             87.1            89.5
yes            12.9            10.5


--famsup--
        Math (%)  Portuguese (%)
famsup
yes         61.3            61.3
no          38.7            38.7


--paid--
      Math (%)  Portuguese (%)
paid
no        54.2            94.0
yes       45.8             6.0


--activities--
            Math (%)  Portuguese (%)
activities
yes             50.9            48.5
no              49.1            51.5


--nursery--
         Math (%)  Portuguese (%)
nursery
yes          79.5            80.3
no           20.5            19.7


--higher--
        Math (%)  Portuguese (%)
higher
yes         94.9            89.4
no           5.1            10.6


--internet--
          Math (%)  Portuguese (%)
internet
yes           83.3            76.7
no            16.7            23.3


--romantic--
          Math (%)  Portuguese (%)
romantic
no            66.6            63.2
yes           33.4            36.8

In [ ]:
ordinal_columns = [  "Medu", "Fedu", "traveltime", "studytime","failures", "famrel",
                    "freetime", "goout", "Dalc", "Walc", "health"]
print("--- Math Ordinal Ranges ---")
for column in ordinal_columns:
    print(f"{column:<12}: {sorted(student_mat[column].unique().tolist())}")

print("\n--- Portuguese Ordinal Ranges ---")
for column in ordinal_columns:
    print(f"{column:<12}: {sorted(student_por[column].unique().tolist())}")

--- Math Ordinal Ranges ---
Medu        : [0, 1, 2, 3, 4]
Fedu        : [0, 1, 2, 3, 4]
traveltime  : [1, 2, 3, 4]
studytime   : [1, 2, 3, 4]
failures    : [0, 1, 2, 3]
famrel      : [1, 2, 3, 4, 5]
freetime    : [1, 2, 3, 4, 5]
goout       : [1, 2, 3, 4, 5]
Dalc        : [1, 2, 3, 4, 5]
Walc        : [1, 2, 3, 4, 5]
health      : [1, 2, 3, 4, 5]

--- Portuguese Ordinal Ranges ---
Medu        : [0, 1, 2, 3, 4]
Fedu        : [0, 1, 2, 3, 4]
traveltime  : [1, 2, 3, 4]
studytime   : [1, 2, 3, 4]
failures    : [0, 1, 2, 3]
famrel      : [1, 2, 3, 4, 5]
freetime    : [1, 2, 3, 4, 5]
goout       : [1, 2, 3, 4, 5]
Dalc        : [1, 2, 3, 4, 5]
Walc        : [1, 2, 3, 4, 5]
health      : [1, 2, 3, 4, 5]

In [ ]:
grades_columns = ["G1", "G2", "G3"]
print("---Math Grades---")
display(student_mat[grades_columns].describe())
print("---Portuguese Grades")
display(student_por[grades_columns].describe())
print(f"Math G3 == 0 count: {(student_mat['G3'] == 0).sum()}")
print(f"Portuguese G3 == 0 count: {(student_por['G3'] == 0).sum()}")

---Math Grades---

               G1          G2          G3
count  395.000000  395.000000  395.000000
mean    10.908861   10.713924   10.415190
std      3.319195    3.761505    4.581443
min      3.000000    0.000000    0.000000
25%      8.000000    9.000000    8.000000
50%     11.000000   11.000000   11.000000
75%     13.000000   13.000000   14.000000
max     19.000000   19.000000   20.000000

---Portuguese Grades

               G1          G2          G3
count  649.000000  649.000000  649.000000
mean    11.399076   11.570108   11.906009
std      2.745265    2.913639    3.230656
min      0.000000    0.000000    0.000000
25%     10.000000   10.000000   10.000000
50%     11.000000   11.000000   12.000000
75%     13.000000   13.000000   14.000000
max     19.000000   19.000000   19.000000

Math G3 == 0 count: 38
Portuguese G3 == 0 count: 15

In [ ]:
numeric_columns = ["age", "absences"]
print("Math Numeric Overview:")
display(student_mat[numeric_columns].describe())
print("Portuguese Numeric Overview:")
display(student_por[numeric_columns].describe())

Math Numeric Overview:

              age    absences
count  395.000000  395.000000
mean    16.696203    5.708861
std      1.276043    8.003096
min     15.000000    0.000000
25%     16.000000    0.000000
50%     17.000000    4.000000
75%     18.000000    8.000000
max     22.000000   75.000000

Portuguese Numeric Overview:

              age    absences
count  649.000000  649.000000
mean    16.744222    3.659476
std      1.218138    4.640759
min     15.000000    0.000000
25%     16.000000    0.000000
50%     17.000000    2.000000
75%     18.000000    6.000000
max     22.000000   32.000000

In [ ]:
print("Math Pass/Fail Proportions:")
print((student_mat["G3"] >= 10).value_counts(normalize=True).round(3))
print("Portuguese Pass/fail Proportions:")
print((student_por["G3"] >= 10).value_counts(normalize=True).round(3))

Math Pass/Fail Proportions:
G3
True     0.671
False    0.329
Name: proportion, dtype: float64
Portuguese Pass/fail Proportions:
G3
True     0.846
False    0.154
Name: proportion, dtype: float64